# Generated by Django 4.2.11 on 2025-11-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YouTubeComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=50)),
                ("comment_id", models.CharField(max_length=100, unique=True)),
                ("author", models.CharField(max_length=100)),
                ("comment_text", models.TextField()),
                ("like_count", models.IntegerField(default=0)),
                ("reply_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField()),
                ("engagement_score", models.FloatField(default=0)),
            ],
            options={"ordering": ["-created_at"],},
        ),
    ]
