# Generated by Django 4.2.11 on 2025-11-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="youtubecomment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "YouTube Comment",
                "verbose_name_plural": "YouTube Comments",
            },
        ),
    ]
