# Generated by Django 4.2.11 on 2025-11-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_youtubecomment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubecomment",
            name="ai_reply",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="youtubecomment",
            name="embedding",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="youtubecomment",
            name="reply_depth_potential",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="youtubecomment",
            name="comment_id",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="youtubecomment",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
