# Generated by Django 4.2.11 on 2025-12-04 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0004_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("free", "無料プラン"),
                            ("pro", "Proプラン"),
                            ("enterprise", "Enterpriseプラン"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="プラン名",
                    ),
                ),
                ("display_name", models.CharField(max_length=100, verbose_name="表示名")),
                ("price", models.IntegerField(default=0, verbose_name="価格（円/月）")),
                (
                    "is_premium",
                    models.BooleanField(default=False, verbose_name="有料プラン"),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "プラン", "verbose_name_plural": "プラン",},
        ),
        migrations.CreateModel(
            name="UserPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="開始日時"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="有効期限"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="myapp.plan",
                        verbose_name="プラン",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_plan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "ユーザープラン", "verbose_name_plural": "ユーザープラン",},
        ),
    ]
