# Generated by Django 4.2.11 on 2025-12-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_plan_userplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                help_text="Stripeダッシュボードで作成した価格ID（例: price_1xxxxxxxxxxxxx）",
                max_length=200,
                null=True,
                verbose_name="Stripe価格ID",
            ),
        ),
    ]
