# Generated by Django 4.2.11 on 2025-12-19 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0006_plan_stripe_price_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubecomment",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="youtube_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="所有者",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                help_text="price_1SaoNrHKU8SnCbsFH2ObkYS4",
                max_length=200,
                null=True,
                verbose_name="Stripe価格ID",
            ),
        ),
    ]
